# Information for parsing database files
dbase_metadata:
  timestamp: 
    name: clean_tv
    dtype: float64
    precision: 8
    base: 719529
    base_unit: D
    resolution: 30min
  traces:
    dtype: float32
    precision: 4
    
stage:
  # All paths assumed to be relative to Database/YYYY/SiteID/ e.g., C:/Users/User/Database/YYYY/SiteID/
  # (see by "user_path_definitions_template.yml")
  Second: Clean/SecondStage
  Third: Clean/ThirdStage
  Third_Default: Clean/ThirdStage_Default_Ustar
  Third_Advanced: Clean/ThirdStage_Full_Ustar_Uncertainty
  Met: Met
  Flux: Flux
  Manual: Met/Manual

